#
# Basic settings.
#
url: http://myeyesareblind.com
baseurl:
title: myeyesareblind
description: iOS Developer by day, lisper by night.<br>Writing on programming topics.
avatar: /assets/img/Kirill.jpg
favicon: /assets/img/hide.png
language: en

#
# Icons
#
icons:
  rss: false
  email: myeyesareblind@gmail.com
  github: myeyesareblind
  bitbucket:
  twitter: myeyesareblnd
  facebook: myeyesareblind
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: UA-96380730-1
disqus: myeyesareblind-com

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons:
  twitter: true
  facebook: false # needs ogp.fb.app_id
  hatena: false
ogp:
  image_url: //ttskch.github.io/jekyll-ttskch-theme/assets/img/ogp.png
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Gems.
#
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
